apiVersion: v1
kind: ServiceAccount
metadata:
  name: concourse-sa
  namespace: blog
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: concourse-role
  namespace: blog
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - projectriff.io
  resources:
  - functions
  - topics
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: concourse-rb
  namespace: blog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: concourse-role
subjects:
- kind: ServiceAccount
  name: concourse-sa
