---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: point-rabbit-pvc
  namespace: blog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: point-rabbit-service
  namespace: blog
  labels:
    app: point-rabbit
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 15672
    name: management
  selector:
    app: point-rabbit
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: point-rabbit
  namespace: blog
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: point-rabbit
    spec:
      containers:
      - image: rabbitmq:3-management
        name: point-rabbit
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: point-rabbit-secret
              key: rabbitmq-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: point-rabbit-secret
              key: rabbitmq-password
        ports:
        - containerPort: 5672
          name: rabbitmq
        - containerPort: 15672
          name: management
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: point-rabbit-pvc