---
apiVersion: v1
kind: Service
metadata:
  name: blog-zipkin-service
  namespace: blog
  labels:
    app: blog-zipkin
spec:
  ports:
  - port: 9411
    name: zipkin
  selector:
    app: blog-zipkin
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-zipkin
  namespace: blog
spec:
  selector:
    matchLabels:
      app: blog-zipkin
  template:
    metadata:
      labels:
        app: blog-zipkin
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9411"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
      - image: openzipkin/zipkin:2.8
        name: blog-zipkin
        env:
        - name: STORAGE_TYPE
          value: mem
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: info,health,prometheus
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: when_authorized
        ports:
        - containerPort: 9411
          name: zipkin
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9411
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9411
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3