---
apiVersion: v1
kind: Service
metadata:
  name: blog-zipkin-service
  namespace: blog
  labels:
    app: blog-zipkin
spec:
  ports:
  - port: 9411
    name: zipkin
  selector:
    app: blog-zipkin
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-zipkin
  namespace: blog
spec:
  selector:
    matchLabels:
      app: blog-zipkin
  template:
    metadata:
      labels:
        app: blog-zipkin
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9411"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
      - image: openzipkin/zipkin:2.8
        name: blog-zipkin
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kafka
        - name: STORAGE_TYPE
          value: mem
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: info,health,prometheus
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: when_authorized
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: blog-kafka-secret
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: ZIPKIN_COLLECTOR_KAFKA_OVERRIDES_AUTO_OFFSET_RESET
          value: latest
        - name: ZIPKIN_COLLECTOR_KAFKA_OVERRIDES_SECURITY_PROTOCOL
          value: SASL_SSL
        - name: ZIPKIN_COLLECTOR_KAFKA_OVERRIDES_SASL_MECHANISM
          value: SCRAM-SHA-256
        - name: ZIPKIN_COLLECTOR_KAFKA_OVERRIDES_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_JAAS_USERNAME}\" password=\"${KAFKA_JAAS_PASSWORD}\";"
        - name: KAFKA_JAAS_USERNAME
          valueFrom:
            secretKeyRef:
              name: blog-kafka-secret
              key: KAFKA_JAAS_USERNAME
        - name: KAFKA_JAAS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blog-kafka-secret
              key: KAFKA_JAAS_PASSWORD
        ports:
        - containerPort: 9411
          name: zipkin
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9411
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9411
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3