---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: blog
  labels:
    app: config-server
spec:
  ports:
  - port: 8888
  selector:
    app: config-server
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: blog
  labels:
    app: config-server
data:
  application.properties: |-
    spring.cloud.config.server.git.uri=https://github.com/making/blog-config.git
    spring.cloud.config.server.default-label=scs
    security.basic.enabled=true
    management.security.enabled=true
    server.tomcat.max-connections=16
    logging.level.root=WARN
    logging.level.org.apache.catalina.filters.RequestDumperFilter=WARN
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
  namespace: blog
  labels:
    app: config-server
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - image: making/config-server:1.3.4.RELEASE
        name: config-server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: _JAVA_OPTIONS
          value: "-Xmx96M -Xss1M -XX:MaxMetaspaceSize=80M -XX:ReservedCodeCacheSize=32M -XX:CompressedClassSpaceSize=16M -XX:MaxDirectMemorySize=16M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP"
        - name: SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: config-server-secret
              key: config-server-user
        - name: SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: config-server-secret
              key: config-server-password
        ports:
        - containerPort: 8888
          name: config-server
        volumeMounts:
        - name: application-config
          mountPath: "/config"
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 15
          timeoutSeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 60
          timeoutSeconds: 15
          periodSeconds: 30
          failureThreshold: 3
      volumes:
      - name: application-config
        configMap:
          name: config-server-config
          items:
          - key: application.properties
            path: application-kubernetes.properties
