---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: point-rabbit-pv
  namespace: blog
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/vcap/store/pv/point-rabbit